---
title: "On the origin of citations"
author: "Sidney"
date: "Sep 15, 2015"
output:
  pdf_document:
    toc: yes
  html_document:
    fig_caption: yes
    fig_height: 8
    fig_width: 8
    highlight: espresso
    theme: cerulean
    toc: yes
---

# load the data
```{r load data, echo=FALSE}
count.raw<-read.delim("/Users/siddisis/Desktop/SWC/altmetrics/data/counts-raw.txt.gz")
count.norm<-read.delim("/Users/siddisis/Desktop/SWC/altmetrics/data/counts-norm.txt.gz")
```

# Data exploration

Dist of author count

```{r author count, fig.cap="Figure 1: Number of Authors per Article", echo=FALSE}
hist(count.raw$authorsCount, main="Author per paper", xlab="# author")
```

```{r fb share, fig.cap="Figure 2: Number of FB share per Article", echo=FALSE}
hist(log10(count.raw$facebookShareCount), main="FB share per paper", xlab="log10 # share")
```

```{r, echo=FALSE}
X <- mean(count.raw$facebookShareCount)
```


The average number of Facebook shares per paper in the data set is `r mean(count.raw$facebookShareCount)`

## dplyr

```{r}
library("dplyr")
```
```{r subsetting}
research <- filter(count.raw,articleType == "Research Article")
```

```{r most cited 11}
research %>%
  arrange(desc(wosCountThru2011)) %>%
  select(title) %>%
  slice(1:3)
```

```{r most author}
research %>%
  arrange(desc(authorsCount)) %>%
  select(authorsCount, title, journal, plosSubjectTags) %>%
  slice(1:3)

```

```{r summarizing with dplyr}

research <- research %>% mutate(weeksSincePublished = daysSincePublished / 7, yearsSincePublished = weeksSincePublished / 52)

select(research, contains("Since")) %>% slice(1:10)


```

```{r}
summarize(research, plos_mean = mean(plosCommentCount), num=n())
```

```{r using group by}
research %>% group_by(journal) %>% summarise(tweet=mean(backtweetsCount))

```

```{r challenge}

research %>% group_by(journal) %>% summarise(num=n(),tweet_mean=mean(backtweetsCount), tweet_SEM=sd(backtweetsCount)/(n())^0.5)->tweet_pj



```



```{r}
library("ggplot2")
```

```{r}

p <- ggplot(data = research, mapping = aes(x=pdfDownloadsCount, y=wosCountThru2011))+geom_point(aes(color = journal))+geom_smooth()


```

```{r}
research <- mutate(research, immuno = grepl("Immunology", plosSubjectTags))
p <- ggplot(data = research, mapping = aes(x=pdfDownloadsCount, y=wosCountThru2011))+geom_point(aes(color = journal))+geom_smooth()
p+facet_grid(journal~immuno)

```



```{r}
p <- ggplot(data = research, mapping = aes(x=daysSincePublished, y=wosCountThru2011, color = journal))+geom_point(alpha=0.5)+geom_smooth(color="red")

```

```{r}

p_box <- ggplot(research, aes(x = journal,
                              y = log10(wosCountThru2011 + 1))) +
  geom_boxplot() +
  scale_y_continuous(breaks = c(1, 3), labels = c(10, 1000))
p_box

```

```{r}
tweet_bar<-ggplot(tweet_pj, aes(x = journal, y = tweet_mean))+geom_bar(stat = "identity")
                                                                                          

```

